"""Tests for parallel WP3 (initial-scoring) — see
docs/superpowers/specs/2026-06-03-parallel-wp3-initial-scoring-design.md."""

import pytest

from synthesis import greedy_partition
from parallel_pipeline import parallel_greedy_partition

# Captured from a sequential run of greedy_partition on the
# synthesis_candidates fixture BEFORE the refactor. This pins the current
# behavior so the refactor in synthesis.py cannot silently change output.
# Generated by the one-off script in Task 2 Step 1.
EXPECTED_PARTITIONS = [[0, 1, 3], [2], [4], [5], [6], [7]]


def _canonical(partitions):
    """Return partitions in a stable comparison form."""
    return sorted(sorted(p) for p in partitions)


def test_refactor_preserves_behavior(synthesis_candidates, tmp_path):
    """greedy_partition on the fixture must keep producing EXPECTED_PARTITIONS."""
    actual = greedy_partition(
        synthesis_candidates,
        tau=-0.2, theta_overlap=1, use_approx=True,
        output_folder=str(tmp_path),
    )
    assert _canonical(actual) == EXPECTED_PARTITIONS


@pytest.mark.parametrize("n_workers", [2, 4])
def test_parallel_equals_sequential(synthesis_candidates, tmp_path, n_workers):
    """parallel_greedy_partition must produce the same partitions as
    greedy_partition for any input — bit-identical, no tie-break drift."""
    seq = greedy_partition(
        synthesis_candidates,
        tau=-0.2, theta_overlap=1, use_approx=True,
        output_folder=str(tmp_path / "seq"),
    )
    par = parallel_greedy_partition(
        synthesis_candidates,
        tau=-0.2, theta_overlap=1, use_approx=True,
        n_workers=n_workers, chunk_size=2,
        output_folder=str(tmp_path / "par"),
    )
    assert _canonical(par) == _canonical(seq)


def test_parallel_n_workers_one(synthesis_candidates, tmp_path):
    """n_workers=1 routes through the parallel code path (still uses a
    Pool) and produces the same output."""
    seq = greedy_partition(
        synthesis_candidates,
        tau=-0.2, theta_overlap=1, use_approx=True,
        output_folder=str(tmp_path / "seq"),
    )
    par = parallel_greedy_partition(
        synthesis_candidates,
        tau=-0.2, theta_overlap=1, use_approx=True,
        n_workers=1, chunk_size=2,
        output_folder=str(tmp_path / "par"),
    )
    assert _canonical(par) == _canonical(seq)


def _trivial(idx, pairs):
    return {"pairs":[tuple(p) for p in pairs],"theta":1.0,
            "row_count":len(pairs),"covered_rows":len(pairs),
            "source_table_index":idx,"left_column_index":0,
            "right_column_index":1,"source_metadata":{}}


def test_parallel_empty(tmp_path):
    """Zero candidates → empty partition list, no Pool created."""
    assert parallel_greedy_partition([], n_workers=2, output_folder=str(tmp_path)) == []


def test_parallel_single_candidate(tmp_path):
    """One candidate → one singleton partition."""
    cands = [_trivial(0, [("a", "x"), ("b", "y"), ("c", "z")])]
    result = parallel_greedy_partition(cands, n_workers=2, output_folder=str(tmp_path))
    assert _canonical(result) == [[0]]


def test_parallel_no_overlap(tmp_path):
    """Candidates with no shared pairs or left values → all singletons."""
    cands = [
        _trivial(0, [("a", "x"), ("b", "y"), ("c", "z")]),
        _trivial(1, [("d", "p"), ("e", "q"), ("f", "r")]),
        _trivial(2, [("g", "m"), ("h", "n"), ("i", "o")]),
    ]
    seq = greedy_partition(cands, output_folder=str(tmp_path / "seq"))
    par = parallel_greedy_partition(cands, n_workers=2, output_folder=str(tmp_path / "par"))
    assert _canonical(par) == _canonical(seq) == [[0], [1], [2]]


def test_parallel_determinism(synthesis_candidates, tmp_path):
    """Running the parallel path twice on identical input produces
    identical output (independent from parallel-vs-sequential equality)."""
    run1 = parallel_greedy_partition(
        synthesis_candidates,
        tau=-0.2, theta_overlap=1, use_approx=True,
        n_workers=4, chunk_size=2, output_folder=str(tmp_path / "r1"),
    )
    run2 = parallel_greedy_partition(
        synthesis_candidates,
        tau=-0.2, theta_overlap=1, use_approx=True,
        n_workers=4, chunk_size=2, output_folder=str(tmp_path / "r2"),
    )
    assert _canonical(run1) == _canonical(run2)


from synthesis import negative_score


def test_negative_score_single_F_matches_paper_eq4():
    """w- = -max(|F| / |B|, |F| / |B'|), F computed once.

    Hand-crafted case:
      B  = [(a, x), (b, y), (c, z)]
      B' = [(a, x), (b, w)]  # conflict on b only
    |F| = 1, |B| = 3, |B'| = 2.
    w- = -max(1/3, 1/2) = -0.5.
    """
    b  = [("a", "x"), ("b", "y"), ("c", "z")]
    bp = [("a", "x"), ("b", "w")]
    assert negative_score(b, bp, use_approx=False) == pytest.approx(-0.5)


def test_negative_score_strict_mode_no_op_under_exact():
    """Under --no_approx the single-F implementation equals
    -max(|f_from_b|/|B|, |f_from_b_prime|/|B'|) because both
    conflict-set sizes are equal under exact left-value matching.
    Constructed example with two conflicts: b uses lefts {a, b, c, d}
    where 'a' and 'b' have right-value mismatches with b'."""
    b  = [("a", "x"), ("b", "y"), ("c", "z"), ("d", "q")]
    bp = [("a", "x1"), ("b", "y1"), ("c", "z"), ("e", "q")]
    score = negative_score(b, bp, use_approx=False)
    # 'a' and 'b' conflict; 'c' matches; 'd' and 'e' don't share left.
    # |F| = 2, |B| = 4, |B'| = 4 → -max(2/4, 2/4) = -0.5.
    assert score == pytest.approx(-0.5)
