"""Tests for parallel WP3 (initial-scoring) — see
docs/superpowers/specs/2026-06-03-parallel-wp3-initial-scoring-design.md."""

import pytest

from synthesis import greedy_partition
from parallel_pipeline import parallel_greedy_partition

# Captured from a sequential run of greedy_partition on the
# synthesis_candidates fixture BEFORE the refactor. This pins the current
# behavior so the refactor in synthesis.py cannot silently change output.
# Generated by the one-off script in Task 2 Step 1.
EXPECTED_PARTITIONS = [[0, 1, 3], [2], [4], [5], [6], [7]]


def _canonical(partitions):
    """Return partitions in a stable comparison form."""
    return sorted(sorted(p) for p in partitions)


def test_refactor_preserves_behavior(synthesis_candidates, tmp_path):
    """greedy_partition on the fixture must keep producing EXPECTED_PARTITIONS."""
    actual = greedy_partition(
        synthesis_candidates,
        tau=-0.2, theta_overlap=1, use_approx=True,
        output_folder=str(tmp_path),
    )
    assert _canonical(actual) == EXPECTED_PARTITIONS


@pytest.mark.parametrize("n_workers", [2, 4])
def test_parallel_equals_sequential(synthesis_candidates, tmp_path, n_workers):
    """parallel_greedy_partition must produce the same partitions as
    greedy_partition for any input — bit-identical, no tie-break drift."""
    seq = greedy_partition(
        synthesis_candidates,
        tau=-0.2, theta_overlap=1, use_approx=True,
        output_folder=str(tmp_path / "seq"),
    )
    par = parallel_greedy_partition(
        synthesis_candidates,
        tau=-0.2, theta_overlap=1, use_approx=True,
        n_workers=n_workers, chunk_size=2,
        output_folder=str(tmp_path / "par"),
    )
    assert _canonical(par) == _canonical(seq)


def test_parallel_n_workers_one(synthesis_candidates, tmp_path):
    """n_workers=1 routes through the parallel code path (still uses a
    Pool) and produces the same output."""
    seq = greedy_partition(
        synthesis_candidates,
        tau=-0.2, theta_overlap=1, use_approx=True,
        output_folder=str(tmp_path / "seq"),
    )
    par = parallel_greedy_partition(
        synthesis_candidates,
        tau=-0.2, theta_overlap=1, use_approx=True,
        n_workers=1, chunk_size=2,
        output_folder=str(tmp_path / "par"),
    )
    assert _canonical(par) == _canonical(seq)
